[package]
name = "datis-core"
version = "1.0.0-alpha.3"
authors = ["Markus Ast <m@rkusa.st>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
audiopus = "0.2"
base64 = "0.10"
bytes = "0.4"
futures-preview = "=0.3.0-alpha.19"
futures-util-preview = "=0.3.0-alpha.19"
log = "0.4"
ogg = "0.7"
reqwest = { version = "0.10.0-alpha.1", features = ["json"] }
rusoto_core = "0.41"
rusoto_credential = "0.41"
rusoto_polly = "0.41"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
srs = { path = "../srs" }
tokio = "0.2.0-alpha.6"