[package]
name = "datis-core"
version = "1.0.0-alpha.7"
authors = ["Markus Ast <m@rkusa.st>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
audiopus = "0.2"
base64 = "0.12"
bytes = "0.5"
futures = "0.3"
log = "0.4"
ogg = "0.7"
reqwest = { version = "0.10", features = ["json"] }
rusoto_core = "0.43"
rusoto_credential = "0.43"
rusoto_polly = "0.43"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
srs = { path = "../srs" }
tokio = { version = "0.2", features = ["time", "rt-threaded"] }

[features]
default = []
static-weather = []