[package]
name = "datis-cmd"
version = "1.0.0-alpha.7"
authors = ["Markus Ast <m@rkusa.st>"]
edition = "2018"

[dependencies]
clap = "2.32"
ctrlc = "3.1"
datis-core = { path = "../datis-core", features = ["static-weather"] }
dotenv = "0.15"
env_logger = "0.7"
log = "0.4"