[package]
name = "datis-core"
version = "0.9.1"
authors = ["Markus Ast <m@rkusa.st>"]
edition = "2018"

[dependencies]
base64 = "0.9"
byteorder = "1.2"
log = "0.4"
ogg = "0.6"
reqwest = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = "0.6"