[package]
name = "datis-cmd"
version = "0.1.0"
authors = ["Markus Ast <m@rkusa.st>"]
edition = "2018"

[dependencies]
clap = "2.32"
ctrlc = "3.1"
datis-core = { path = "../datis-core" }
dotenv = "0.14"
env_logger = "0.5"
log = "0.4"