[package]
name = "datis"
version = "2.0.0"
authors = ["Markus Ast <m@rkusa.st>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
const-cstr = "0.3"
datis-core = { path = "../datis-core" }
hlua51 = { git = "https://github.com/rkusa/hlua51.git" }
libc = "0.2"
log = "0.4"
log4rs = "0.12"
lua51-sys = { git = "https://github.com/rkusa/hlua51.git" }
rand = "0.7.3"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"