[package]
name = "datis"
version = "2.2.0-beta.2"
authors = ["Markus Ast <m@rkusa.st>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
datis-core = { path = "../datis-core" }
log4rs = "0.13"
log = "0.4"
mlua = { version = "0.4", default-features = false, features = ["lua51", "module"] }
mlua_derive = "0.4"
once_cell = "1.4.0"
rand = "0.7.3"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_mlua = { git = "https://github.com/rkusa/serde_mlua.git", branch = "master" }
thiserror = "1.0"