[package]
name = "srs"
version = "1.0.0-alpha.7"
authors = ["rkusa"]
edition = "2018"

[dependencies]
anyhow = "1.0"
base64 = "0.12"
byteorder = "1.3"
bytes = "0.5"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["time", "udp"] }
tokio-util = { version = "0.3", features = ["codec", "udp"] }
uuid = { version = "0.8", features = ["v4"] }
