name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Switch to Rust beta
      run: rustup override set beta
    - name: Run tests
      run: cargo test
