name: Rust

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update Rust
      run: rustup update
    - name: Run tests
      env:
        LUA_LIB_NAME: lua
        LUA_LIB: ${{github.workspace}}/lua5.1/
        LUA_INC: ${{github.workspace}}/lua5.1/include
      run: cargo test
